name: .NET MAUI Windows CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET MAUI workloads
        run: dotnet workload install maui-android maui-windows

      # Each build will automatically restore dependencies for its TFM

      - name: Build WinUI
        run: dotnet build NomenDeutsch.csproj -c Release -f net9.0-windows10.0.19041.0

      - name: Build Android
        run: dotnet build NomenDeutsch.csproj -c Release -f net9.0-android

      # Optional: Test or artifact upload steps go here

      # Optional: Run tests if you have them
      #- name: Test
      #  run: dotnet test --no-build --verbosity normal
      #  continue-on-error: true

      # Optional: Publish artifact step for master
      - name: Publish Windows Artifacts
        if: github.ref == 'refs/heads/master'
        run: echo "Publish or upload Windows build artifacts here!"